/**
 * Rebuild every `.claude/agent-memory/<agent>/MEMORY.md` index from the notes
 * beside it.
 *
 * The index is a pointer list — one line per note — that Claude Code loads into
 * a subagent's context so it can pick which note to open. Every line is already
 * derivable from the note it points at: the link text is that note's
 * frontmatter `name:`, the hook after the em dash is its `description:`.
 *
 * It used to be hand-appended and tracked in git, which cost two things (#129):
 *
 *   - Two PRs in flight that both recorded a memory for the *same* agent
 *     appended to the same line of the same file and collided. The correct
 *     resolution is always the union of all entries, which is not what the
 *     conflict hunk shows — a third party's entry can already be missing from
 *     both sides — so a careless resolve deletes a note's pointer silently.
 *   - The hook duplicated the note's own `description:`, so one claim lived in
 *     three places (note body, frontmatter, index line) and correcting one left
 *     two. Both copies have shipped a claim the other contradicted: the index
 *     lines for `project_flush_refusal_barrier_pg113` and
 *     `project_signed_body_framing_headers_83` each described a gap their own
 *     note said was closed (see the commit that folded the hooks into the
 *     descriptions, and the discussion on the issue).
 *
 * Deriving the file removes both classes: it is generated, git-ignored, and the
 * `description:` is the single source of the index text. The notes themselves
 * stay tracked — they are the memory; this file is only a table of contents.
 *
 * Usage:
 *   bun scripts/agent-memory-index.ts           # rewrite every index
 *   bun scripts/agent-memory-index.ts --check   # verify only, write nothing (CI)
 */
import { existsSync, lstatSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

/** Repository root, resolved from this file rather than the working directory. */
export const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url))

/** Directory holding one sub-directory of notes per agent, relative to the root. */
export const MEMORY_ROOT = '.claude/agent-memory'

/** Absolute path of {@link MEMORY_ROOT} — a hook or CI step can run from anywhere. */
export const MEMORY_DIR = join(REPO_ROOT, MEMORY_ROOT)

/** The index file inside each agent directory. Generated, never hand-edited. */
export const INDEX_NAME = 'MEMORY.md'

/**
 * Header written above the entries.
 *
 * Claude Code appends to `MEMORY.md` itself when an agent records a memory, so
 * the banner has to tell both a human and an agent that a hand-written line is
 * transient — it survives only until the next rebuild, and the durable place
 * for that text is the note's own `description:`.
 */
export const INDEX_BANNER = `<!-- Generated by scripts/agent-memory-index.ts from the \`name:\`/\`description:\`
     frontmatter of the notes in this directory (issue #129). Not tracked in git, and
     hand edits do not survive: to change a line, edit that note's \`description:\`.
     Rebuild with \`bun scripts/agent-memory-index.ts\`. -->`

/** One note reduced to what the index needs, plus anything wrong with it. */
export interface NoteEntry {
  /** File name of the note, relative to its agent directory. */
  file: string
  /** Frontmatter `name:`, falling back to the file stem. */
  name: string
  /** Frontmatter `description:`; empty when the note has none. */
  description: string
  /** Human-readable defects — a note is still indexed when it has some. */
  problems: string[]
}

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/
// Two separate reasons the value group is spelled `(\S.*)?` and not `(.*)`,
// both load-bearing and neither obvious:
//   - the `?` is what makes a bare `metadata:` capture `undefined` instead of
//     `''`, which is how `parseFrontmatter` below tells a nested-mapping opener
//     apart from a scalar whose value is empty. Verified: with `(.*)` the group
//     captures `''` for `metadata:` and the distinction is gone.
//   - `\S` keeps the value class disjoint from the `[ \t]*` before it, so the
//     two cannot match the same character and the match stays linear
//     (eslint `regexp/no-super-linear-backtracking`). It does *not* affect what
//     is captured — `[ \t]*` is greedy, so `(.*)?` captures the same text.
const TOP_LEVEL_KEY = /^([a-z][\w-]*):[ \t]*(\S.*)?$/i

/**
 * A YAML block-scalar header — `>` or `|`, with an optional explicit indent
 * (a single digit) and chomping indicator (`+`/`-`) in **either** order, which
 * is what the YAML block-header production allows: `>-`, `|+`, `>2`, `|2-`,
 * `>+2` are all legal.
 *
 * The value is carried by the indented lines that follow, so the header itself
 * must not become the value: `description: >` would otherwise index as the
 * literal `>` with the real text folded onto it.
 */
const BLOCK_SCALAR = /^[|>](?:[1-9][+-]?|[+-][1-9]?)?$/

/**
 * The YAML double-quoted escapes that stand for one character.
 *
 * Unescaping only `\"` and `\\` is not enough: in a double-quoted scalar every
 * one of these is the character, not the two letters, so leaving them alone
 * puts a literal `\n` in the index where the note said a space.
 */
const DOUBLE_QUOTED_ESCAPES: Record<string, string> = {
  '0': '\0',
  'a': '\x07',
  'b': '\b',
  't': '\t',
  'n': '\n',
  'v': '\v',
  'f': '\f',
  'r': '\r',
  'e': '\x1B',
  ' ': ' ',
  '"': '"',
  '/': '/',
  '\\': '\\',
  'N': '\x85',
  '_': '\xA0',
  'L': '\u2028',
  'P': '\u2029',
}

/** Resolve the escape sequences of a YAML double-quoted scalar's body. */
function unescapeDoubleQuoted(body: string): string {
  return body.replace(
    /\\(x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8}|[\s\S])/g,
    (match, escape: string) => {
      if (escape.length > 1) {
        // `\U` admits eight digits, which reach far past the last code point,
        // and `String.fromCodePoint` throws on those. A malformed note has to
        // come back as a reported problem, never as a crash that takes the
        // whole run — and every other note with it — down with it.
        const codePoint = Number.parseInt(escape.slice(1), 16)
        return codePoint <= 0x10FFFF ? String.fromCodePoint(codePoint) : match
      }
      // An escape YAML does not define is invalid YAML rather than something to
      // guess at, so it is left exactly as written instead of being swallowed.
      return DOUBLE_QUOTED_ESCAPES[escape] ?? match
    },
  )
}

/**
 * Strip one layer of YAML quoting from a scalar.
 *
 * The memory tool writes plain scalars, but a `description:` containing `": "`
 * has to be quoted to stay valid YAML, so both forms must round-trip.
 */
function unquote(value: string): string {
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return unescapeDoubleQuoted(value.slice(1, -1))
  }
  if (value.length >= 2 && value.startsWith('\'') && value.endsWith('\'')) {
    return value.slice(1, -1).replace(/''/g, '\'')
  }
  return value
}

/**
 * Read the top-level scalars out of a note's frontmatter block.
 *
 * Deliberately not a YAML parser: it needs `name` and `description` and nothing
 * else. A key whose value is empty (`metadata:`) opens a nested mapping whose
 * indented lines are skipped; a key whose value is not empty absorbs following
 * indented lines as a folded continuation, which is how a long `description:`
 * wraps.
 */
export function parseFrontmatter(text: string): Record<string, string | undefined> {
  const block = FRONTMATTER.exec(text)
  if (!block) {
    return {}
  }

  const scalars: Record<string, string | undefined> = {}
  let key: string | null = null

  for (const line of block[1].split(/\r?\n/)) {
    const top = TOP_LEVEL_KEY.exec(line)
    if (top) {
      const [, name, value] = top
      key = value === undefined ? null : name
      if (key) {
        // A block-scalar header opens a value the following indented lines
        // carry, so start empty and let the continuation branch fill it. Both
        // `>` and `|` end up folded onto one line, which is all an index line
        // can be.
        scalars[key] = BLOCK_SCALAR.test(value) ? '' : value
      }
      continue
    }
    // Only an *indented* line continues the previous non-empty scalar — that is
    // what folding means in YAML, and it is also what keeps a column-0 comment
    // line out of the value above it. An indented `#` is left alone on purpose:
    // inside a folded scalar it is literal text, and these descriptions are full
    // of issue references that a comment-stripping parser would eat.
    if (key && /^[ \t]/.test(line) && line.trim() !== '') {
      scalars[key] = `${scalars[key] ?? ''} ${line.trim()}`
    }
  }

  // Collapsed after unquoting, not before, and that order is load-bearing: an
  // index entry is one line of a markdown list, and a double-quoted `\n` only
  // becomes a newline once `unquote` has decoded it. Folding here means no
  // description can split its own list item, whatever notation wrote it.
  for (const [name, value] of Object.entries(scalars)) {
    scalars[name] = unquote((value ?? '').trim()).replace(/\s+/g, ' ').trim()
  }

  return scalars
}

/**
 * Escape the characters that would end a markdown link label early.
 *
 * `name:` is free text an agent wrote, and a `]` in it would truncate the
 * pointer line into something that no longer resolves to the note. Only the
 * label needs this: the `description:` that follows sits outside any link
 * construct, where a bare parenthesis is just a parenthesis.
 */
function escapeLabel(text: string): string {
  return text.replace(/([[\]\\])/g, '\\$1')
}

const ENCODER = new TextEncoder()

/**
 * Render a file name as a markdown link destination.
 *
 * The label is not the only half that can be truncated, and two different
 * layers can break it. `(`, `)`, `<`, `>` and whitespace end the destination in
 * the *markdown* parse; `#`, `?`, `%` and `:` survive that and then carry
 * meaning in the *URL*, where `a#b.md` addresses `a` with a fragment rather
 * than the file, and `review:notes.md` reads `review` as a URI scheme.
 * Percent-encoding covers both, and touches nothing in an ordinary
 * `some_note.md`.
 *
 * Percent-encoding is defined over UTF-8 *bytes*, and `\s` reaches past ASCII:
 * a non-breaking space is one JS character but two bytes, so encoding the code
 * unit would emit `%A0` where the path needs `%C2%A0`. `TextEncoder` is what
 * makes the two agree. (`encodeURIComponent` would not: it leaves `(` and `)`
 * unescaped, and those are exactly what ends a bare markdown destination.)
 */
function linkTarget(file: string): string {
  return file.replace(/[%#?:()<>\s]/g, character =>
    Array.from(ENCODER.encode(character), byte =>
      `%${byte.toString(16).toUpperCase().padStart(2, '0')}`).join(''))
}

/** Reduce one note file to its index entry. */
export function noteEntry(file: string, text: string): NoteEntry {
  const scalars = parseFrontmatter(text)
  const problems: string[] = []

  if (!FRONTMATTER.test(text)) {
    problems.push('has no `---` frontmatter block')
  }
  else if (!scalars.name) {
    problems.push('frontmatter has no `name:`')
  }

  if (!scalars.description) {
    problems.push('frontmatter has no `description:` — it is the index text, so the note lists without one')
  }

  return {
    file,
    name: scalars.name || file.replace(/\.md$/, ''),
    description: scalars.description ?? '',
    problems,
  }
}

/**
 * Render the index for one agent.
 *
 * Sorted by file name so the output depends only on the set of notes, never on
 * the order they were written or the order the filesystem returns them.
 */
export function renderIndex(entries: NoteEntry[]): string {
  const lines = [...entries]
    .sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : 0))
    .map(entry => `- [${escapeLabel(entry.name)}](${linkTarget(entry.file)}) — ${
      entry.description || '(no description — add one to this note\'s frontmatter)'
    }`)

  return `${[INDEX_BANNER, '', ...lines].join('\n')}\n`
}

/** Agent directories under `root`, in a stable order. */
export function agentDirs(root: string): string[] {
  if (!existsSync(root)) {
    return []
  }
  return readdirSync(root, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()
}

/** Notes in one agent directory — every `.md` file except the index itself. */
export function readNotes(dir: string): NoteEntry[] {
  return readdirSync(dir, { withFileTypes: true })
    // Excluding directories rather than selecting regular files: a directory
    // named `*.md` would otherwise reach `readFileSync` as `EISDIR`, while
    // `isFile()` would quietly drop a symlinked note, which is a real note.
    .filter(entry => !entry.isDirectory() && entry.name.endsWith('.md') && entry.name !== INDEX_NAME)
    .map(entry => entry.name)
    .sort()
    .map(file => noteEntry(file, readFileSync(join(dir, file), 'utf8')))
}

/**
 * Index files that are still tracked by git.
 *
 * This is the invariant the fix rests on: an index that re-enters the index
 * (git's, that is) brings the whole conflict class back with it, and no other
 * check in the repo reads that file. So an empty result has to mean the
 * invariant was checked and holds, never that checking failed — see the spawn
 * below, which raises rather than answering `[]` on a git it could not run.
 */
export function trackedIndexFiles(cwd: string = REPO_ROOT): string[] {
  // Spawned the way `scripts/bump-version.ts` shells out to cargo, and checked
  // the same way — on the exit code. Only "not a work tree" may answer `[]`:
  // that is the value meaning *the invariant holds*, so a git that failed for
  // any other reason (missing binary, unreadable index, a sandbox that blocks
  // it) must raise rather than report an all-clear nobody verified.
  // `-z` is not a detail: without it git C-quotes any path holding a non-ASCII
  // character, a quote or a backslash, so `agent-mémoire/MEMORY.md` arrives as
  // `"agent-m\303\251moire/MEMORY.md"` and ends in `"` — the suffix filter
  // below would miss it and report the all-clear this function exists to earn.
  const listed = Bun.spawnSync(['git', 'ls-files', '-z', '--', MEMORY_ROOT], { cwd })
  if (!listed.success) {
    const stderr = listed.stderr.toString()
    if (/not a git repository/i.test(stderr)) {
      return []
    }
    throw new Error(`git ls-files failed (exit ${listed.exitCode}): ${stderr.trim()}`)
  }
  return listed.stdout.toString().split('\0').filter(path => path.endsWith(`/${INDEX_NAME}`))
}

interface Result {
  /** Indexes whose on-disk content differed from the generated content. */
  written: string[]
  /** `<agent>/<note>: <problem>` for every defect found. */
  problems: string[]
}

/** Rebuild (or, with `check`, only inspect) every index under `root`. */
export function rebuild(root: string, options: { check?: boolean } = {}): Result {
  const written: string[] = []
  const problems: string[] = []

  for (const agent of agentDirs(root)) {
    const dir = join(root, agent)
    const notes = readNotes(dir)
    for (const note of notes) {
      for (const problem of note.problems) {
        problems.push(`${agent}/${note.file}: ${problem}`)
      }
    }

    const indexPath = join(dir, INDEX_NAME)
    const rendered = renderIndex(notes)

    // Before reading, and before the equality check: an index is a file this
    // script owns and overwrites unconditionally, so it must not be reachable
    // through a symlink — `writeFileSync` follows one and would clobber
    // whatever a branch pointed it at. `lstat` rather than `existsSync`,
    // because `existsSync` follows the link too and answers false for a
    // dangling one, which is the case that would otherwise be *created* here.
    const link = lstatSync(indexPath, { throwIfNoEntry: false })
    if (link?.isSymbolicLink()) {
      problems.push(`${agent}/${INDEX_NAME}: is a symlink; an index is generated in place, refusing to write through it`)
      continue
    }

    const current = link ? readFileSync(indexPath, 'utf8') : null
    if (current === rendered) {
      continue
    }

    written.push(indexPath)
    if (!options.check) {
      writeFileSync(indexPath, rendered)
    }
  }

  return { written, problems }
}

/**
 * The exit code for a run that wrote every index and then reported defects in
 * the notes behind them.
 *
 * This is the one failure a caller may reasonably carry on from, so it has to
 * be distinguishable from the two that follow: one exit code for all of them
 * makes `|| true` the only option — the swallow this script exists to argue
 * against. The other two are `EXIT_INVARIANT`, and 1 for a run that could not
 * happen at all, which an uncaught throw produces.
 */
export const EXIT_PROBLEMS = 2

/**
 * The exit code for a broken repository invariant — today, an index that is
 * tracked by git again.
 *
 * Separate from `EXIT_PROBLEMS` because **nothing was written**: the run stops
 * before rebuilding so the tree is left as found, which means a caller that
 * tolerates a malformed note must not tolerate this one and call the result an
 * index.
 */
export const EXIT_INVARIANT = 3

function report(problems: string[], code: number): number {
  console.error('agent-memory index problems:')
  for (const problem of problems) {
    console.error(`  - ${problem}`)
  }
  return code
}

/**
 * Returns the process exit code: `EXIT_INVARIANT` when an index is tracked
 * again (nothing is written), `EXIT_PROBLEMS` when every index was written but
 * a note cannot supply its line, 0 when clean. `root` and `cwd` are defaulted
 * for the CLI and only passed by the tests, which need a checkout of their own.
 */
export function main(argv: string[], root: string = MEMORY_DIR, cwd: string = REPO_ROOT): number {
  const check = argv.includes('--check')

  // Checked *and acted on* before rebuilding, not after: `rebuild` writes, and
  // a run that ends in a non-zero exit has written by then. A tracked index is
  // a broken invariant, so the tree is left exactly as found and the run stops.
  const tracked = trackedIndexFiles(cwd)
  if (tracked.length > 0) {
    return report(tracked.map(trackedIndex =>
      `${trackedIndex} is tracked by git — it is generated (issue #129). `
      + `Run \`git rm --cached ${trackedIndex}\`.`), EXIT_INVARIANT)
  }

  const { written, problems } = rebuild(root, { check })

  if (problems.length > 0) {
    return report(problems, EXIT_PROBLEMS)
  }

  if (check) {
    console.log(`agent-memory index: ${written.length} file(s) would be rewritten, no problems`)
  }
  else {
    console.log(`agent-memory index: rebuilt ${written.length} file(s)`)
  }

  return 0
}

if (import.meta.main) {
  process.exit(main(process.argv.slice(2)))
}
