/**
 * Rebuild every `.claude/agent-memory/<agent>/MEMORY.md` index from the notes
 * beside it.
 *
 * The index is a pointer list — one line per note — that Claude Code loads into
 * a subagent's context so it can pick which note to open. Every line is already
 * derivable from the note it points at: the link text is that note's
 * frontmatter `name:`, the hook after the em dash is its `description:`.
 *
 * It used to be hand-appended and tracked in git, which cost two things (#129):
 *
 *   - Two PRs in flight that both recorded a memory for the *same* agent
 *     appended to the same line of the same file and collided. The correct
 *     resolution is always the union of all entries, which is not what the
 *     conflict hunk shows — a third party's entry can already be missing from
 *     both sides — so a careless resolve deletes a note's pointer silently.
 *   - The hook duplicated the note's own `description:`, so one claim lived in
 *     three places (note body, frontmatter, index line) and correcting one left
 *     two. Both copies have shipped a claim the other contradicted: the index
 *     lines for `project_flush_refusal_barrier_pg113` and
 *     `project_signed_body_framing_headers_83` each described a gap their own
 *     note said was closed (see the commit that folded the hooks into the
 *     descriptions, and the discussion on the issue).
 *
 * Deriving the file removes both classes: it is generated, git-ignored, and the
 * `description:` is the single source of the index text. The notes themselves
 * stay tracked — they are the memory; this file is only a table of contents.
 *
 * Usage:
 *   bun scripts/agent-memory-index.ts           # rewrite every index
 *   bun scripts/agent-memory-index.ts --check   # verify only, write nothing (CI)
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

/** Repository root, resolved from this file rather than the working directory. */
export const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url))

/** Directory holding one sub-directory of notes per agent, relative to the root. */
export const MEMORY_ROOT = '.claude/agent-memory'

/** Absolute path of {@link MEMORY_ROOT} — a hook or CI step can run from anywhere. */
export const MEMORY_DIR = join(REPO_ROOT, MEMORY_ROOT)

/** The index file inside each agent directory. Generated, never hand-edited. */
export const INDEX_NAME = 'MEMORY.md'

/**
 * Header written above the entries.
 *
 * Claude Code appends to `MEMORY.md` itself when an agent records a memory, so
 * the banner has to tell both a human and an agent that a hand-written line is
 * transient — it survives only until the next rebuild, and the durable place
 * for that text is the note's own `description:`.
 */
export const INDEX_BANNER = `<!-- Generated by scripts/agent-memory-index.ts from the \`name:\`/\`description:\`
     frontmatter of the notes in this directory (issue #129). Not tracked in git, and
     hand edits do not survive: to change a line, edit that note's \`description:\`.
     Rebuild with \`bun scripts/agent-memory-index.ts\`. -->`

/** One note reduced to what the index needs, plus anything wrong with it. */
export interface NoteEntry {
  /** File name of the note, relative to its agent directory. */
  file: string
  /** Frontmatter `name:`, falling back to the file stem. */
  name: string
  /** Frontmatter `description:`; empty when the note has none. */
  description: string
  /** Human-readable defects — a note is still indexed when it has some. */
  problems: string[]
}

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/
// Two separate reasons the value group is spelled `(\S.*)?` and not `(.*)`,
// both load-bearing and neither obvious:
//   - the `?` is what makes a bare `metadata:` capture `undefined` instead of
//     `''`, which is how `parseFrontmatter` below tells a nested-mapping opener
//     apart from a scalar whose value is empty. Verified: with `(.*)` the group
//     captures `''` for `metadata:` and the distinction is gone.
//   - `\S` keeps the value class disjoint from the `[ \t]*` before it, so the
//     two cannot match the same character and the match stays linear
//     (eslint `regexp/no-super-linear-backtracking`). It does *not* affect what
//     is captured — `[ \t]*` is greedy, so `(.*)?` captures the same text.
const TOP_LEVEL_KEY = /^([a-z][\w-]*):[ \t]*(\S.*)?$/i

/**
 * A YAML block-scalar header — `>` or `|`, with an optional explicit indent
 * (a single digit) and chomping indicator (`+`/`-`) in **either** order, which
 * is what the YAML block-header production allows: `>-`, `|+`, `>2`, `|2-`,
 * `>+2` are all legal.
 *
 * The value is carried by the indented lines that follow, so the header itself
 * must not become the value: `description: >` would otherwise index as the
 * literal `>` with the real text folded onto it.
 */
const BLOCK_SCALAR = /^[|>](?:[1-9][+-]?|[+-][1-9]?)?$/

/**
 * Strip one layer of YAML quoting from a scalar.
 *
 * The memory tool writes plain scalars, but a `description:` containing `": "`
 * has to be quoted to stay valid YAML, so both forms must round-trip.
 */
function unquote(value: string): string {
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1).replace(/\\(["\\])/g, '$1')
  }
  if (value.length >= 2 && value.startsWith('\'') && value.endsWith('\'')) {
    return value.slice(1, -1).replace(/''/g, '\'')
  }
  return value
}

/**
 * Read the top-level scalars out of a note's frontmatter block.
 *
 * Deliberately not a YAML parser: it needs `name` and `description` and nothing
 * else. A key whose value is empty (`metadata:`) opens a nested mapping whose
 * indented lines are skipped; a key whose value is not empty absorbs following
 * indented lines as a folded continuation, which is how a long `description:`
 * wraps.
 */
export function parseFrontmatter(text: string): Record<string, string | undefined> {
  const block = FRONTMATTER.exec(text)
  if (!block) {
    return {}
  }

  const scalars: Record<string, string | undefined> = {}
  let key: string | null = null

  for (const line of block[1].split(/\r?\n/)) {
    const top = TOP_LEVEL_KEY.exec(line)
    if (top) {
      const [, name, value] = top
      key = value === undefined ? null : name
      if (key) {
        // A block-scalar header opens a value the following indented lines
        // carry, so start empty and let the continuation branch fill it. Both
        // `>` and `|` end up folded onto one line, which is all an index line
        // can be.
        scalars[key] = BLOCK_SCALAR.test(value) ? '' : value
      }
      continue
    }
    // Only an *indented* line continues the previous non-empty scalar — that is
    // what folding means in YAML, and it is also what keeps a column-0 comment
    // line out of the value above it. An indented `#` is left alone on purpose:
    // inside a folded scalar it is literal text, and these descriptions are full
    // of issue references that a comment-stripping parser would eat.
    if (key && /^[ \t]/.test(line) && line.trim() !== '') {
      scalars[key] = `${scalars[key] ?? ''} ${line.trim()}`
    }
  }

  for (const [name, value] of Object.entries(scalars)) {
    scalars[name] = unquote((value ?? '').trim()).replace(/\s+/g, ' ').trim()
  }

  return scalars
}

/**
 * Escape the characters that would end a markdown link label early.
 *
 * `name:` is free text an agent wrote, and a `]` in it would truncate the
 * pointer line into something that no longer resolves to the note. Only the
 * label needs this: the `description:` that follows sits outside any link
 * construct, where a bare parenthesis is just a parenthesis.
 */
function escapeLabel(text: string): string {
  return text.replace(/([[\]\\])/g, '\\$1')
}

/**
 * Render a file name as a markdown link destination.
 *
 * The label is not the only half that can be truncated: `)` ends a bare
 * destination, `#` starts a fragment, and whitespace ends it too — any of which
 * points the line at something other than the note. Angle brackets take all of
 * them literally, so they are used only when the name needs them, leaving an
 * ordinary `some_note.md` written plainly.
 */
function linkTarget(file: string): string {
  return /[()#<>\s]/.test(file) ? `<${file.replace(/([<>])/g, '\\$1')}>` : file
}

/** Reduce one note file to its index entry. */
export function noteEntry(file: string, text: string): NoteEntry {
  const scalars = parseFrontmatter(text)
  const problems: string[] = []

  if (!FRONTMATTER.test(text)) {
    problems.push('has no `---` frontmatter block')
  }
  else if (!scalars.name) {
    problems.push('frontmatter has no `name:`')
  }

  if (!scalars.description) {
    problems.push('frontmatter has no `description:` — it is the index text, so the note lists without one')
  }

  return {
    file,
    name: scalars.name || file.replace(/\.md$/, ''),
    description: scalars.description ?? '',
    problems,
  }
}

/**
 * Render the index for one agent.
 *
 * Sorted by file name so the output depends only on the set of notes, never on
 * the order they were written or the order the filesystem returns them.
 */
export function renderIndex(entries: NoteEntry[]): string {
  const lines = [...entries]
    .sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : 0))
    .map(entry => `- [${escapeLabel(entry.name)}](${linkTarget(entry.file)}) — ${
      entry.description || '(no description — add one to this note\'s frontmatter)'
    }`)

  return `${[INDEX_BANNER, '', ...lines].join('\n')}\n`
}

/** Agent directories under `root`, in a stable order. */
export function agentDirs(root: string): string[] {
  if (!existsSync(root)) {
    return []
  }
  return readdirSync(root, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()
}

/** Notes in one agent directory — every `.md` file except the index itself. */
export function readNotes(dir: string): NoteEntry[] {
  return readdirSync(dir, { withFileTypes: true })
    // Excluding directories rather than selecting regular files: a directory
    // named `*.md` would otherwise reach `readFileSync` as `EISDIR`, while
    // `isFile()` would quietly drop a symlinked note, which is a real note.
    .filter(entry => !entry.isDirectory() && entry.name.endsWith('.md') && entry.name !== INDEX_NAME)
    .map(entry => entry.name)
    .sort()
    .map(file => noteEntry(file, readFileSync(join(dir, file), 'utf8')))
}

/**
 * Index files that are still tracked by git.
 *
 * This is the invariant the fix rests on: an index that re-enters the index
 * (git's, that is) brings the whole conflict class back with it, and no other
 * check in the repo reads that file. So an empty result has to mean the
 * invariant was checked and holds, never that checking failed — see the spawn
 * below, which raises rather than answering `[]` on a git it could not run.
 */
export function trackedIndexFiles(cwd: string = REPO_ROOT): string[] {
  // Spawned the way `scripts/bump-version.ts` shells out to cargo, and checked
  // the same way — on the exit code. Only "not a work tree" may answer `[]`:
  // that is the value meaning *the invariant holds*, so a git that failed for
  // any other reason (missing binary, unreadable index, a sandbox that blocks
  // it) must raise rather than report an all-clear nobody verified.
  const listed = Bun.spawnSync(['git', 'ls-files', '--', MEMORY_ROOT], { cwd })
  if (!listed.success) {
    const stderr = listed.stderr.toString()
    if (/not a git repository/i.test(stderr)) {
      return []
    }
    throw new Error(`git ls-files failed (exit ${listed.exitCode}): ${stderr.trim()}`)
  }
  return listed.stdout.toString().split('\n').filter(path => path.endsWith(`/${INDEX_NAME}`))
}

interface Result {
  /** Indexes whose on-disk content differed from the generated content. */
  written: string[]
  /** `<agent>/<note>: <problem>` for every defect found. */
  problems: string[]
}

/** Rebuild (or, with `check`, only inspect) every index under `root`. */
export function rebuild(root: string, options: { check?: boolean } = {}): Result {
  const written: string[] = []
  const problems: string[] = []

  for (const agent of agentDirs(root)) {
    const dir = join(root, agent)
    const notes = readNotes(dir)
    for (const note of notes) {
      for (const problem of note.problems) {
        problems.push(`${agent}/${note.file}: ${problem}`)
      }
    }

    const indexPath = join(dir, INDEX_NAME)
    const rendered = renderIndex(notes)
    const current = existsSync(indexPath) ? readFileSync(indexPath, 'utf8') : null
    if (current === rendered) {
      continue
    }

    written.push(indexPath)
    if (!options.check) {
      writeFileSync(indexPath, rendered)
    }
  }

  return { written, problems }
}

/**
 * Returns the process exit code: non-zero when any note cannot be indexed, or
 * when an index is tracked again. `root` and `cwd` are defaulted for the CLI
 * and only passed by the tests, which need a checkout of their own.
 */
export function main(argv: string[], root: string = MEMORY_DIR, cwd: string = REPO_ROOT): number {
  const check = argv.includes('--check')
  const { written, problems } = rebuild(root, { check })

  for (const tracked of trackedIndexFiles(cwd)) {
    problems.push(
      `${tracked} is tracked by git — it is generated (issue #129). `
      + `Run \`git rm --cached ${tracked}\`.`,
    )
  }

  if (problems.length > 0) {
    console.error('agent-memory index problems:')
    for (const problem of problems) {
      console.error(`  - ${problem}`)
    }
    return 1
  }

  if (check) {
    console.log(`agent-memory index: ${written.length} file(s) would be rewritten, no problems`)
  }
  else {
    console.log(`agent-memory index: rebuilt ${written.length} file(s)`)
  }

  return 0
}

if (import.meta.main) {
  process.exit(main(process.argv.slice(2)))
}
