/**
 * Rebuild every `.claude/agent-memory/<agent>/MEMORY.md` index from the notes
 * beside it.
 *
 * The index is a pointer list — one line per note — that Claude Code loads into
 * a subagent's context so it can pick which note to open. Every line is already
 * derivable from the note it points at: the link text is that note's
 * frontmatter `name:`, the hook after the em dash is its `description:`.
 *
 * It used to be hand-appended and tracked in git, which cost two things (#129):
 *
 *   - Two PRs in flight that both recorded a memory for the *same* agent
 *     appended to the same line of the same file and collided. The correct
 *     resolution is always the union of all entries, which is not what the
 *     conflict hunk shows — a third party's entry can already be missing from
 *     both sides — so a careless resolve deletes a note's pointer silently.
 *   - The hook duplicated the note's own `description:`, so one claim lived in
 *     three places (note body, frontmatter, index line) and correcting one left
 *     two. Both copies have shipped a claim the other contradicted: the index
 *     lines for `project_flush_refusal_barrier_pg113` and
 *     `project_signed_body_framing_headers_83` each described a gap their own
 *     note said was closed (see the commit that folded the hooks into the
 *     descriptions, and the discussion on the issue).
 *
 * Deriving the file removes both classes: it is generated, git-ignored, and the
 * `description:` is the single source of the index text. The notes themselves
 * stay tracked — they are the memory; this file is only a table of contents.
 *
 * Usage:
 *   bun scripts/agent-memory-index.ts           # rewrite every index
 *   bun scripts/agent-memory-index.ts --check   # verify only, write nothing (CI)
 */
import { existsSync, lstatSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

/** Repository root, resolved from this file rather than the working directory. */
export const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url))

/** Directory holding one sub-directory of notes per agent, relative to the root. */
export const MEMORY_ROOT = '.claude/agent-memory'

/** Absolute path of {@link MEMORY_ROOT} — a hook or CI step can run from anywhere. */
export const MEMORY_DIR = join(REPO_ROOT, MEMORY_ROOT)

/** The index file inside each agent directory. Generated, never hand-edited. */
export const INDEX_NAME = 'MEMORY.md'

/**
 * Header written above the entries.
 *
 * Claude Code appends to `MEMORY.md` itself when an agent records a memory, so
 * the banner has to tell both a human and an agent that a hand-written line is
 * transient — it survives only until the next rebuild, and the durable place
 * for that text is the note's own `description:`.
 */
export const INDEX_BANNER = `<!-- Generated by scripts/agent-memory-index.ts from the \`name:\`/\`description:\`
     frontmatter of the notes in this directory (issue #129). Not tracked in git, and
     hand edits do not survive: to change a line, edit that note's \`description:\`.
     Rebuild with \`bun scripts/agent-memory-index.ts\`. -->`

/** One note reduced to what the index needs, plus anything wrong with it. */
export interface NoteEntry {
  /** File name of the note, relative to its agent directory. */
  file: string
  /** Frontmatter `name:`, falling back to the file stem. */
  name: string
  /** Frontmatter `description:`; empty when the note has none. */
  description: string
  /** Human-readable defects — a note is still indexed when it has some. */
  problems: string[]
}

const FRONTMATTER = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/

/**
 * Whitespace that would break the index's single line, or pad its edges.
 *
 * Deliberately not `\s`: that class holds the no-break space and its
 * relatives, which are *content* — flattening one to an ordinary space, or
 * letting `trim` eat one off an edge, made the index text differ from the value
 * the note's frontmatter yields, which is the whole defect this index removes.
 * `\s` also omits NEL (`\N`), which really does break a line, so the class is
 * spelled out either way.
 */
const LINE_WHITESPACE = /[\t\n\v\f\r \u0085\u2028\u2029]+/g

/** The only frontmatter this index renders, and so the only part it judges. */
const INDEXED_KEYS = ['name', 'description'] as const

/** What a note's frontmatter block yields: its scalars, and why any is suspect. */
export interface Frontmatter {
  scalars: Record<string, string | undefined>
  problems: string[]
}

/**
 * The first character YAML's own character set excludes, if the text holds one.
 *
 * A transcription of the spec's `c-printable` production, negated, and the one
 * piece of YAML written out here rather than asked of the parser — because
 * `Bun.YAML` does not implement this production. Measured on Bun 1.4.2: of
 * U+0000, U+0001, U+0008, U+001F, U+007F, U+0080, U+009F it refuses only
 * U+0000 and reads the rest through into the value, where they would be
 * written verbatim into a generated markdown index.
 *
 * That is worth keeping a rule for, and it is not the kind of rule this file
 * stopped keeping: it is a closed set of code points, not a judgement about
 * what a scalar's *source* looked like, so it needs nothing the parser knows
 * and cannot be widened by the next shape of YAML anyone writes. A stricter
 * reader refuses these in its *reader*, before a parse begins, so one anywhere
 * in the frontmatter makes the note unloadable — quoting does not rescue it.
 * The escaped form (`"before\0after"`) is a different thing and stays legal.
 *
 * Written as codepoint arithmetic rather than a character class because a
 * regular expression spelling the C0 controls is what `no-control-regex`
 * exists to catch, and this file would be the repository's first
 * `eslint-disable`. Iterating the string yields whole codepoints, so an
 * astral character is one character here and not two halves.
 */
function forbiddenCharacter(text: string): string | undefined {
  return [...text].find((character) => {
    const point = character.codePointAt(0) ?? 0
    return !(point === 0x09 || point === 0x0A || point === 0x0D
      || (point >= 0x20 && point <= 0x7E)
      || point === 0x85
      || (point >= 0xA0 && point <= 0xD7FF)
      || (point >= 0xE000 && point <= 0xFFFD)
      || point >= 0x10000)
  })
}

/** A YAML mapping, which is the only shape a frontmatter block may have. */
type Mapping = Record<string, unknown>

/**
 * Whether a parsed document is a mapping this reader can take keys from.
 *
 * A sequence is the only other object `Bun.YAML` builds. It resolves no scalar
 * to a `Date` — a bare `2026-09-13`, an ISO datetime and an explicit
 * `!!timestamp` tag all come back as text, because YAML 1.2's core schema has
 * no timestamp type — so there is no third object shape to exclude here.
 */
function isMapping(value: unknown): value is Mapping {
  return typeof value === 'object'
    && value !== null
    && !Array.isArray(value)
}

/** A parsed document, or the reason the parser refused it. */
type Read = { document: unknown } | { reason: string }

/**
 * `Bun.YAML.parse`, with a throw turned into a reason.
 *
 * Every malformed note has to come back as a *reported problem*: this script
 * rebuilds every agent's index in one pass, so an uncaught throw would take
 * every other note's index down with the one bad note (#156 fixed exactly that
 * failure mode once already, for a different cause).
 */
function readYaml(source: string): Read {
  try {
    return { document: Bun.YAML.parse(source) }
  }
  catch (error) {
    return { reason: error instanceof Error ? error.message : String(error) }
  }
}

/**
 * The frontmatter line at which the document stops being readable.
 *
 * `Bun.YAML`'s `SyntaxError` carries no position — its `line`/`column` point at
 * the `parse` call site in this file, not into the YAML — and "not valid YAML"
 * with no location is not an actionable report for someone holding a twenty
 * line frontmatter block. The location is recovered from the parser instead of
 * guessed at: the longest prefix of lines that still reads is the last line
 * that can be right, so the line after it is where the reader gave up.
 *
 * The *longest* readable prefix, not the first unreadable one. A quoted scalar
 * that wraps makes its own opening line unreadable on its own (`description: "a`
 * closes nothing yet) and readable again once the closing line arrives, so the
 * first prefix that throws is routinely a line with nothing wrong with it.
 *
 * One parse per line over a block whose own length grows with the line count is
 * quadratic work, so the scan is bounded. Every committed note's frontmatter is
 * five or six lines and no note has a reason to be longer, but nothing in the
 * format stops one — a body pasted inside the fence would reach here on a path
 * that runs in CI, in `mise run install` and in every new worktree's setup.
 * Past the bound the block goes unlocated rather than slow: a note that large
 * is malformed in a way its author can see without a line number.
 */
const LOCATABLE_LINES = 200

function failingLine(lines: string[]): { number: number, text: string } | undefined {
  if (lines.length > LOCATABLE_LINES) {
    return undefined
  }
  let readable = 0
  for (let count = 1; count <= lines.length; count++) {
    if (!('reason' in readYaml(lines.slice(0, count).join('\n')))) {
      readable = count
    }
  }
  const line = lines[readable]
  // Only the trailing edge is trimmed. A line's *leading* whitespace is often
  // the defect being reported — a tab where indentation goes, a block scalar's
  // content one column short — so trimming it away would hide the thing the
  // reader is being pointed at.
  return line === undefined ? undefined : { number: readable + 1, text: line.replace(/\s+$/, '') }
}

/**
 * Two characters the note does not already use, to stand in for the ones a
 * comment probe masks.
 *
 * Private-use code points: YAML admits them as ordinary characters, and nothing
 * a note is written in resolves to one. They are *found* rather than fixed,
 * because a fixed pair only holds while no note contains it — a note that did
 * would have turned the probe off, and turning a check off on the strength of
 * the note's own content is how a reader stops reading. There are 6400 of them
 * and two are needed, so a note has to carry 6399 distinct ones to run this out.
 *
 * Both the source *and* what it resolves to are searched, because those differ:
 * `description: "quoted \\uE000 # still text"` holds no private-use character as
 * text, and holds one after the parser decodes the escape. Searching the source
 * alone picks U+E000, the restore step then rewrites the note's own character
 * along with the mask, and a correctly quoted value is reported as cut. The
 * comparison is against resolved values, so that is where the stand-ins have to
 * be absent from.
 */
const PRIVATE_USE_FIRST = 0xE000
const PRIVATE_USE_LAST = 0xF8FF

function probeCharacters(source: string, mapping: Mapping): [string, string] | undefined {
  const resolved = Object.values(mapping).filter(value => typeof value === 'string').join('')
  let first: string | undefined
  for (let point = PRIVATE_USE_FIRST; point <= PRIVATE_USE_LAST; point++) {
    const character = String.fromCodePoint(point)
    if (source.includes(character) || resolved.includes(character)) {
      continue
    }
    if (first === undefined) {
      first = character
      continue
    }
    return [first, character]
  }
  return undefined
}

/**
 * A mapping key the note does not already carry, to rename one occurrence of a
 * key to while the parser is asked whether that key was written twice. Suffixed
 * until it is absent, for the same reason the probe characters are searched
 * for: a name that collides must not read as "nothing to check here".
 *
 * Absent from the *resolved keys* as well as the source text, and for the same
 * reason the mask characters are: those differ. A note can spell a top-level
 * key `"agent-memory-index-duplicate-probe":`, which no `source.includes`
 * sees and which the parser resolves to the probe name. The test after the
 * rename is `key in probed.document`, and that only means "the rename put it
 * there" while the note did not have it already — otherwise a nomination that
 * lands in a block scalar or a nested mapping, creating no root key at all,
 * still reads as one, and valid frontmatter is rejected as a duplicate.
 */
function probeKey(source: string, mapping: Mapping): string {
  let key = 'agent-memory-index-duplicate-probe'
  for (let suffix = 0; source.includes(key) || key in mapping; suffix++) {
    key = `agent-memory-index-duplicate-probe-${suffix}`
  }
  return key
}

/**
 * Offsets of every `#` in `source` that could open a comment mid-line.
 *
 * YAML starts a comment at a `#` that follows a space or a tab. Two are left
 * out, because neither can cut text out of a value and masking either changes
 * what the document *is*:
 *
 *   - a `#` with no separator in front of it (`covers (#154) fully`) is
 *     ordinary text to every reader;
 *   - a `#` that is the first thing on its line is a whole-line comment, and
 *     turning one into content puts a bare scalar where the reader expects a
 *     key — the probe would fail to parse rather than answer anything.
 */
function* inlineHashes(source: string): Generator<number> {
  let lineStart = 0
  for (let offset = 0; offset < source.length; offset++) {
    const character = source[offset]
    if (character === '\n' || character === '\r') {
      lineStart = offset + 1
      continue
    }
    if (character !== '#') {
      continue
    }
    const before = source.slice(lineStart, offset)
    // Ends with a separator, so the `#` opens a comment; and holds something
    // that is not one, so the comment does not start the line.
    if (/[ \t]$/.test(before) && /[^ \t]/.test(before)) {
      yield offset
    }
  }
}

/**
 * A copy of `source` in which the `#` at `offset` no longer opens a comment.
 *
 * The `#` is not the only thing that has to change. Everything after it was
 * comment text, written under no grammar at all, and once the `#` stops hiding
 * it the parser reads it as YAML — so a comment holding `: ` (`description:
 * fixed in PR #155: see docs`) turns the line into an attempted nested mapping
 * and the probe fails to parse. That failure is indistinguishable from the one
 * a probe is *supposed* to skip, so the probe would answer "nothing to see" for
 * exactly the value it was asked about. Masking the line's remaining `:` as
 * well leaves it a plain scalar; both stand-ins are put back before the
 * comparison, so the value being compared is the note's own text.
 */
function maskComment(source: string, offset: number, hash: string, colon: string): string {
  const rest = source.slice(offset).search(/[\r\n]/)
  const stop = rest === -1 ? source.length : offset + rest
  const masked = source.slice(offset, stop).replaceAll('#', hash).replaceAll(':', colon)
  return `${source.slice(0, offset)}${masked}${source.slice(stop)}`
}

/**
 * Report an indexed value whose text YAML cut at a comment.
 *
 * The commonest thing a YAML reader does *silently* to a scalar, and the defect
 * that forced 36 of the committed notes to be quoted (#156): the author writes
 * `description: fixed in PR #155, so do X` and every reader resolves
 * `fixed in PR`, so the index would advertise a summary that stops mid-sentence
 * and nothing would say why.
 *
 * Asked of the parser rather than decided here. Masking one `#` and reading the
 * document again says exactly what that `#` hid — no rule about which scalars
 * are plain, which is the enumeration this file was rewritten to stop keeping:
 * a `#` inside quotes or block content comes back in the same place and the
 * values match, while one that opened a comment comes back with the rest of the
 * line attached.
 *
 * One `#` at a time, so a probe the parser still refuses costs only that one
 * `#`. Every refusal left is a comment following a **closed node** — a quoted
 * scalar (`description: "text" # note`) or a flow collection
 * (`description: [a, b] # note`) — where unmasking puts content where a key
 * belongs. That is the one class where the skip costs nothing: the node ended
 * before the `#`, so no comment cut it. A quoted scalar comes back whole, and a
 * flow collection is not text at all and is reported as such by the caller.
 * Measured over 1890 probes across the scalar and comment shapes, no other
 * shape refuses, and an oracle over 306 plain values missed no cut.
 */
function commentedOut(source: string, mapping: Mapping, problems: string[]): void {
  // Nothing to mask means nothing to answer, and a note with no inline `#` is
  // not owed a report about the reader's ability to probe one.
  const offsets = [...inlineHashes(source)]
  if (offsets.length === 0) {
    return
  }
  const probes = probeCharacters(source, mapping)
  if (probes === undefined) {
    problems.push('the frontmatter uses every private-use character, leaving this reader nothing to mask a `#` with — it cannot check whether a comment cut a value short')
    return
  }
  const [hash, colon] = probes
  const reported = new Set<string>()
  for (const offset of offsets) {
    if (reported.size === INDEXED_KEYS.length) {
      return
    }
    const probed = readYaml(maskComment(source, offset, hash, colon))
    if ('reason' in probed || !isMapping(probed.document)) {
      continue
    }
    for (const name of INDEXED_KEYS) {
      const resolved = mapping[name]
      const whole = probed.document[name]
      // Only a value that survived as text can have had text cut off it. A
      // value the comment consumed entirely (`description: # write this later`)
      // is null, which is the *absence* of a description — `noteEntry` reports
      // that, and reporting it twice, once as a truncation, says the note has a
      // summary it does not have.
      if (reported.has(name) || typeof resolved !== 'string' || typeof whole !== 'string') {
        continue
      }
      if (whole.replaceAll(hash, '#').replaceAll(colon, ':') !== resolved) {
        reported.add(name)
        problems.push(`\`${name}:\` is unquoted and contains \` #\`, which YAML reads as the start of a comment — quote the value so it survives`)
      }
    }
  }
}

/**
 * A quoted scalar sitting where a mapping key goes, with its quotes.
 *
 * Written to be *wide*: what it selects is ruled on by the parser, so a quoted
 * value picked up by mistake costs one tiny parse and a quoted key missed costs
 * a report.
 *
 * `[\s\S]` after the backslash, not `.`, because a backslash escapes the *next
 * character* and JavaScript's `.` stops at a line terminator. A double-quoted
 * scalar may be continued across lines by escaping the newline, and where YAML
 * allows a multi-line key — an explicit key, or inside a flow mapping —
 * `? "descri\<newline>  ption"` is the key `description`. Matching only up to
 * the line end would end the token in the middle and nominate nothing.
 */
const QUOTED_KEY = /(['"])(?:\\[\s\S]|(?!\1)[^\\])*\1(?=[ \t\r\n]*[:\r\n])/g

/**
 * Where in the block a key is written, over every spelling of it.
 *
 * Three shapes reach the same mapping key and discard a repeat as silently as
 * each other: the bare `description:`, an explicit key (`? description` over
 * `: text`), and any quoted spelling — `"description":`, `'description':`, and
 * `"description":`, which is the same key to a reader that decodes escapes.
 *
 * That last one is why the quoted spellings are not matched by name. Deciding
 * from the source what `"description"` spells means decoding YAML escapes
 * here, and a transcription of the escape table is the scanner this file
 * replaced. The parser is asked instead: a quoted key token *is* a YAML
 * document, so reading it says which key it is, and no escape rule is written
 * here at all.
 *
 * Each offset carries a length because the rename replaces what was matched:
 * the name for a bare key, the whole token — quotes and all — for a quoted one.
 *
 * **Where this stops, on purpose.** What is nominated is a key whose spelling is
 * lexically *here*, at the key position. A key whose identity is defined
 * somewhere else in the document is not: `? &k description` / `: first` over
 * `? *k` / `: second` resolves both entries to `description` and drops `first`
 * without a word (#205). Covering it means resolving anchors — finding anchor
 * definitions, mapping each to the key it spells, then finding alias tokens in
 * key position — three more source patterns, which is how the scanner this file
 * replaced reached thirty-one review rounds.
 *
 * The line is drawn here rather than one spelling further along because nothing
 * closes this set while the parser exposes no structure: `Bun.YAML` gives no
 * CST, no token stream and no positions, so locating a key is lexical work that
 * cannot be delegated. What *is* delegated is every semantic question — the
 * parser says what a token spells and whether an occurrence is really a repeat.
 * The index stays correct either way: it publishes what the parser resolved, so
 * a missed report costs the author a warning, never the reader a wrong summary.
 */
function keyOccurrences(source: string, name: string): { at: number, length: number }[] {
  // Loose on purpose: this only *nominates* offsets for the parser to rule on,
  // so one nominated wrongly costs a probe and one missed costs a report, never
  // a wrong one. `String.raw`, because a plain template literal decodes the
  // `\s`/`\t` and puts the characters themselves in the pattern — which matches
  // much the same thing but reads as an accident.
  const bare = new RegExp(String.raw`(^|[\s{,])((?:\?[ \t]+)?)${name}[ \t]*(?=[:\r\n])`, 'g')
  const found = [...source.matchAll(bare)].map(match => ({
    at: match.index + match[1].length + match[2].length,
    length: name.length,
  }))
  for (const match of source.matchAll(QUOTED_KEY)) {
    const spelled = readYaml(match[0])
    if (!('reason' in spelled) && spelled.document === name) {
      found.push({ at: match.index, length: match[0].length })
    }
  }
  return found
}

/**
 * Report an indexed key the note gives more than once.
 *
 * The second silent discard. YAML requires a mapping key to be unique;
 * Bun.YAML and pyyaml both keep the last of a repeat rather than refusing the
 * document, so the index would not *drift* from them — but the author wrote two
 * summaries and one disappeared without a word, and a stricter reader (js-yaml)
 * rejects the note outright.
 *
 * Asked of the parser for the same reason as the comment probe: renaming one
 * occurrence and reading the document again answers "was this key at the root
 * twice" without this file having to decide where the root is. That decision is
 * what round 30 of #156 got wrong — an outer key the scanner could not spell
 * (`my.key:`) left the root indentation undecided and a nested `description:`
 * was published as the note's own. A rename of a *nested* occurrence puts the
 * probe key inside the nested mapping, where this test does not see it.
 *
 * Occurrences are nominated by offset in the block rather than by line, and
 * across every spelling that reaches the same key — see `keyOccurrences`. Which
 * of them is *really* a repeat is still the parser's answer, not the pattern's.
 */
function repeated(source: string, mapping: Mapping, problems: string[]): void {
  const key = probeKey(source, mapping)
  for (const name of INDEXED_KEYS) {
    if (!(name in mapping)) {
      continue
    }
    const occurrences = keyOccurrences(source, name)
    if (occurrences.length < 2) {
      continue
    }
    for (const { at, length } of occurrences) {
      const probed = readYaml(`${source.slice(0, at)}${key}${source.slice(at + length)}`)
      if ('reason' in probed || !isMapping(probed.document)) {
        continue
      }
      if (key in probed.document && name in probed.document) {
        problems.push(`\`${name}:\` is given more than once, and YAML requires a mapping key to be unique — keep the one that is the summary and delete the other`)
        break
      }
    }
  }
}

/** Name what YAML resolved a value to, for a note that meant it as text. */
function describeValue(value: unknown): string {
  if (Array.isArray(value)) {
    return 'a sequence'
  }
  if (isMapping(value)) {
    return 'a mapping'
  }
  // `String`, not `JSON.stringify`: `description: .inf` resolves to `Infinity`,
  // which JSON has no spelling for and stringifies as `null` — a report naming
  // the wrong value is worse than one naming none.
  return `the ${typeof value} \`${String(value)}\``
}

/**
 * Flatten a resolved value onto the one line an index entry is.
 *
 * Runs on what the parser returned, not on the source spelling, so it applies
 * to every notation equally: a block scalar's trailing newline, a folded
 * scalar's line breaks and a double-quoted `\n` all reach here as the
 * characters they stand for. Only the one space folding can add is stripped
 * from the edges — a no-break space at either end is the note's own character.
 */
function foldOntoOneLine(value: string): string {
  return value.replace(LINE_WHITESPACE, ' ').replace(/^ | $/g, '')
}

/**
 * Read the top-level scalars out of a note's frontmatter block.
 *
 * The frontmatter is read by `Bun.YAML`, a real YAML parser, rather than by a
 * scanner written here. The scanner this replaces was eleven review rounds of
 * an enumeration that does not terminate (#168): every round found another
 * shape of YAML it and a real reader resolved differently, and three of the
 * fixes moved a boundary the other rules had been written against. A parser has
 * those interactions settled by its grammar.
 *
 * What a parser does *not* do is report, and reporting is the load-bearing half
 * here — the index must not quietly advertise something other than what the
 * note's frontmatter yields. So four things are reported rather than resolved:
 *
 *   - a character YAML does not admit at all, which `Bun.YAML` mostly does not
 *     refuse (it stops only at U+0000) and would otherwise carry into the index
 *     verbatim;
 *   - a block the parser refuses, which is a note no reader can load;
 *   - a value that resolves to something that is not text (`42`, `[a]`), which
 *     is not a summary whatever it is;
 *   - the two things YAML discards in silence — the text after an inline `#`,
 *     and every occurrence but the last of a repeated key. Both are asked of
 *     the parser, by reading a doctored copy of the block and comparing.
 */
export function parseFrontmatter(text: string): Frontmatter {
  const block = FRONTMATTER.exec(text)
  if (!block) {
    return { scalars: {}, problems: [] }
  }

  const source = block[1]
  const problems: string[] = []

  const forbidden = forbiddenCharacter(source)
  if (forbidden !== undefined) {
    const point = (forbidden.codePointAt(0) ?? 0).toString(16).toUpperCase().padStart(4, '0')
    problems.push(`the frontmatter holds U+${point}, which YAML does not allow as a character — a reader may refuse the note over it or carry it into the index unchanged, so write it as an escape in a double-quoted value`)
  }

  const read = readYaml(source)
  if ('reason' in read) {
    const at = failingLine(source.split(/\r?\n/))
    problems.push(`the frontmatter is not valid YAML — ${read.reason}${
      at ? ` (line ${at.number}: \`${at.text}\`)` : ''}`)
    return { scalars: {}, problems }
  }

  // An empty block yields no document at all. That is a note with no `name:`
  // and no `description:`, which `noteEntry` reports as such; it is not a
  // separate defect, and calling it "not a mapping" would say the frontmatter
  // is malformed when it is merely blank.
  if (read.document === null || read.document === undefined) {
    return { scalars: {}, problems }
  }

  if (!isMapping(read.document)) {
    problems.push(`the frontmatter is ${describeValue(read.document)}, not a mapping of \`name:\` and \`description:\` — this reader has no keys to take from it`)
    return { scalars: {}, problems }
  }

  const mapping = read.document
  const scalars: Record<string, string | undefined> = {}
  for (const [key, value] of Object.entries(mapping)) {
    if (typeof value === 'string') {
      scalars[key] = foldOntoOneLine(value)
    }
  }

  for (const name of INDEXED_KEYS) {
    const value = mapping[name]
    // Absent, or `null` — which is what YAML resolves `description:`,
    // `description: null`, `description: ~` and `description: # todo` alike to.
    // All four are the absence of a description, and `noteEntry` reports that
    // once, in the words the author needs to hear.
    if (value === undefined || value === null || typeof value === 'string') {
      continue
    }
    problems.push(`\`${name}:\` is ${describeValue(value)} rather than text — quote it if the value really is that word`)
  }

  commentedOut(source, mapping, problems)
  repeated(source, mapping, problems)

  return { scalars, problems }
}

/**
 * Escape the characters that would end a markdown link label early.
 *
 * `name:` is free text an agent wrote, and a `]` in it would truncate the
 * pointer line into something that no longer resolves to the note. Only the
 * label needs this: the `description:` that follows sits outside any link
 * construct, where a bare parenthesis is just a parenthesis.
 */
function escapeLabel(text: string): string {
  return text.replace(/([[\]\\])/g, '\\$1')
}

const ENCODER = new TextEncoder()

/** File-name characters a markdown link destination can carry as themselves. */
const UNRESERVED = /[^\w.~-]/gu

/**
 * Render a file name as a markdown link destination.
 *
 * **Everything outside `UNRESERVED` is encoded, rather than a list of the
 * characters known to break.** That list was tried first and leaked three
 * times: `(` and whitespace end the destination in the *markdown* parse, then
 * `#`, `?` and `%` survive that and carry meaning in the *URL*, then `:` makes
 * `review:notes.md` read as a URI scheme, then `\` resolves as a path
 * separator. Each was a true finding against an enumeration that could only
 * ever be as complete as the last person to think about it. Naming the safe
 * characters instead — and a file name is under no obligation to hold only
 * those — makes the set closed: an unforeseen character is encoded by default,
 * which is inert, instead of emitted raw, which is a link to the wrong file.
 *
 * Percent-encoding is defined over UTF-8 *bytes*, so the encoder runs over
 * bytes, not JS characters: a non-breaking space is one character and two
 * bytes, and `%A0` would not be the path. The `u` flag is part of the same
 * point at the other end of the range — without it the match is per UTF-16
 * code unit, so an astral name like `a😀b.md` arrives as two lone surrogates
 * and each encodes to the replacement character rather than to the emoji. (`encodeURIComponent` is not this
 * function: it leaves `(`, `)` and `!*'` unescaped, and the first two are
 * exactly what ends a bare markdown destination.)
 */
function linkTarget(file: string): string {
  return file.replace(UNRESERVED, character =>
    Array.from(ENCODER.encode(character), byte =>
      `%${byte.toString(16).toUpperCase().padStart(2, '0')}`).join(''))
}

/** Reduce one note file to its index entry. */
export function noteEntry(file: string, text: string): NoteEntry {
  const { scalars, problems } = parseFrontmatter(text)

  if (!FRONTMATTER.test(text)) {
    problems.push('has no `---` frontmatter block')
  }
  else if (!scalars.name) {
    problems.push('frontmatter has no `name:`')
  }

  if (!scalars.description) {
    problems.push('frontmatter has no `description:` — it is the index text, so the note lists without one')
  }

  return {
    file,
    name: scalars.name || file.replace(/\.md$/, ''),
    description: scalars.description ?? '',
    problems,
  }
}

/**
 * Render the index for one agent.
 *
 * Sorted by file name so the output depends only on the set of notes, never on
 * the order they were written or the order the filesystem returns them.
 */
export function renderIndex(entries: NoteEntry[]): string {
  const lines = [...entries]
    .sort((a, b) => (a.file < b.file ? -1 : a.file > b.file ? 1 : 0))
    .map(entry => `- [${escapeLabel(entry.name)}](${linkTarget(entry.file)}) — ${
      entry.description || '(no description — add one to this note\'s frontmatter)'
    }`)

  return `${[INDEX_BANNER, '', ...lines].join('\n')}\n`
}

/** Agent directories under `root`, in a stable order. */
export function agentDirs(root: string): string[] {
  if (!existsSync(root)) {
    return []
  }
  return readdirSync(root, { withFileTypes: true })
    .filter(entry => entry.isDirectory())
    .map(entry => entry.name)
    .sort()
}

/** Notes in one agent directory — every `.md` file except the index itself. */
export function readNotes(dir: string): NoteEntry[] {
  return readdirSync(dir, { withFileTypes: true })
    // Excluding directories rather than selecting regular files: a directory
    // named `*.md` would otherwise reach `readFileSync` as `EISDIR`, while
    // `isFile()` would quietly drop a symlinked note, which is a real note.
    .filter(entry => !entry.isDirectory() && entry.name.endsWith('.md') && entry.name !== INDEX_NAME)
    .map(entry => entry.name)
    .sort()
    .map(file => noteEntry(file, readFileSync(join(dir, file), 'utf8')))
}

/**
 * Index files that are still tracked by git.
 *
 * This is the invariant the fix rests on: an index that re-enters the index
 * (git's, that is) brings the whole conflict class back with it, and no other
 * check in the repo reads that file. So an empty result has to mean the
 * invariant was checked and holds, never that checking failed — see the spawn
 * below, which raises rather than answering `[]` on a git it could not run.
 */
export function trackedIndexFiles(cwd: string = REPO_ROOT): string[] {
  // Spawned the way `scripts/bump-version.ts` shells out to cargo, and checked
  // the same way — on the exit code. Only "not a git repository" may answer
  // `[]`: that is the value meaning *the invariant holds*, so a git that
  // failed for any other reason (missing binary, unreadable index, a sandbox
  // that blocks it) must raise rather than report an all-clear nobody
  // verified. A bare repository is not one of those reasons — `ls-files` there
  // exits 0 with no output, so it reaches the same `[]` down the success path.
  // `-z` is not a detail: without it git C-quotes any path holding a non-ASCII
  // character, a quote or a backslash, so `agent-mémoire/MEMORY.md` arrives as
  // `"agent-m\303\251moire/MEMORY.md"` and ends in `"` — the suffix filter
  // below would miss it and report the all-clear this function exists to earn.
  const listed = Bun.spawnSync(['git', 'ls-files', '-z', '--', MEMORY_ROOT], { cwd })
  if (!listed.success) {
    const stderr = listed.stderr.toString()
    if (/not a git repository/i.test(stderr)) {
      return []
    }
    throw new Error(`git ls-files failed (exit ${listed.exitCode}): ${stderr.trim()}`)
  }
  return listed.stdout.toString().split('\0').filter(path => path.endsWith(`/${INDEX_NAME}`))
}

interface Result {
  /** Indexes whose on-disk content differed from the generated content. */
  written: string[]
  /** `<agent>/<note>: <problem>` for every note defect found. */
  problems: string[]
  /**
   * Reasons an index could not be written at all.
   *
   * Kept apart from `problems` because the two mean opposite things to a
   * caller: a note defect leaves a complete index with one placeholder line in
   * it, while anything here leaves that agent with no index. Folding them
   * together is what made `EXIT_PROBLEMS` claim more than it could keep.
   */
  refusals: string[]
}

/** Rebuild (or, with `check`, only inspect) every index under `root`. */
export function rebuild(root: string, options: { check?: boolean } = {}): Result {
  const written: string[] = []
  const problems: string[] = []
  const refusals: string[] = []

  // Every index path is inspected before any of them is written. Doing it per
  // agent inside one loop meant an earlier agent's index was already on disk by
  // the time a later one was refused, so a run that reported "nothing was
  // written" had written — the same clause-vs-code gap, one scope out.
  const refusedAgents = new Set<string>()
  for (const agent of agentDirs(root)) {
    const indexPath = join(root, agent, INDEX_NAME)
    // Not just a symlink: a directory at an index path passed a symlink-only
    // preflight and then threw `EISDIR` on read, once an earlier agent's index
    // was already on disk — the very outcome this pass exists to prevent. Any
    // existing path that is not a regular file is refused here instead.
    const existing = lstatSync(indexPath, { throwIfNoEntry: false })
    if (existing && !existing.isFile()) {
      refusals.push(existing.isSymbolicLink()
        ? `${agent}/${INDEX_NAME}: is a symlink; an index is generated in place, refusing to write through it`
        : `${agent}/${INDEX_NAME}: is not a regular file; an index is generated in place, refusing to write over it`)
      refusedAgents.add(agent)
    }
  }
  // Not an early return: the notes are still read and their defects still
  // reported, so one invocation names everything it found rather than making
  // the refusal hide a malformed note that will fail the next run too. What a
  // refusal stops is the *writing*, below.
  const refused = refusals.length > 0

  for (const agent of agentDirs(root)) {
    const dir = join(root, agent)
    const notes = readNotes(dir)
    for (const note of notes) {
      for (const problem of note.problems) {
        problems.push(`${agent}/${note.file}: ${problem}`)
      }
    }

    // Its notes are read and reported like everyone else's; its index path is
    // not ours to read either — a dangling link `lstat`s fine and then throws
    // on open, which is the same trap `existsSync` set at the other end.
    if (refusedAgents.has(agent)) {
      continue
    }

    const indexPath = join(dir, INDEX_NAME)
    const rendered = renderIndex(notes)

    // `lstat` rather than `existsSync` throughout: `existsSync` follows a
    // symlink, so it cannot be used to detect one, and it answers false for a
    // dangling link — the case where the write would *create* the target. The
    // refusal pass above has already ruled every index path out or in.
    const current = lstatSync(indexPath, { throwIfNoEntry: false })
      ? readFileSync(indexPath, 'utf8')
      : null
    if (current === rendered) {
      continue
    }

    if (refused) {
      continue
    }

    written.push(indexPath)
    if (!options.check) {
      writeFileSync(indexPath, rendered)
    }
  }

  return { written, problems, refusals }
}

/**
 * The exit code for a run that wrote every index and then reported defects in
 * the notes behind them.
 *
 * This is the one failure a caller may reasonably carry on from, so it has to
 * be distinguishable from the two that follow: one exit code for all of them
 * makes `|| true` the only option — the swallow this script exists to argue
 * against. The other two are `EXIT_INVARIANT`, and 1 for a run that could not
 * happen at all, which an uncaught throw produces.
 */
export const EXIT_PROBLEMS = 2

/**
 * The exit code for a broken invariant — an index that is tracked by git
 * again, or one that cannot be written because a symlink stands where it goes.
 *
 * Separate from `EXIT_PROBLEMS` because **nothing was written**: the run stops
 * before rebuilding so the tree is left as found, which means a caller that
 * tolerates a malformed note must not tolerate this one and call the result an
 * index.
 */
export const EXIT_INVARIANT = 3

function report(problems: string[], code: number): number {
  console.error('agent-memory index problems:')
  for (const problem of problems) {
    console.error(`  - ${problem}`)
  }
  return code
}

/**
 * Returns the process exit code: `EXIT_INVARIANT` when an index is tracked
 * again or could not be written, `EXIT_PROBLEMS` when every index was written
 * but a note cannot supply its line, 0 when clean. `root` and `cwd` are defaulted
 * for the CLI and only passed by the tests, which need a checkout of their own.
 */
export function main(argv: string[], root: string = MEMORY_DIR, cwd: string = REPO_ROOT): number {
  const check = argv.includes('--check')

  // Checked *and acted on* before rebuilding, not after: `rebuild` writes, and
  // a run that ends in a non-zero exit has written by then. A tracked index is
  // a broken invariant, so the tree is left exactly as found and the run stops.
  const tracked = trackedIndexFiles(cwd)
  if (tracked.length > 0) {
    return report(tracked.map(trackedIndex =>
      `${trackedIndex} is tracked by git — it is generated (issue #129). `
      + `Run \`git rm --cached ${trackedIndex}\`.`), EXIT_INVARIANT)
  }

  const { written, problems, refusals } = rebuild(root, { check })

  // Refusals first, and at the invariant code: they mean an agent has no index,
  // which a caller tolerating a malformed note must not be told to carry on
  // from. Reported together so one run names everything it found.
  if (refusals.length > 0) {
    return report([...refusals, ...problems], EXIT_INVARIANT)
  }

  if (problems.length > 0) {
    return report(problems, EXIT_PROBLEMS)
  }

  if (check) {
    console.log(`agent-memory index: ${written.length} file(s) would be rewritten, no problems`)
  }
  else {
    console.log(`agent-memory index: rebuilt ${written.length} file(s)`)
  }

  return 0
}

if (import.meta.main) {
  process.exit(main(process.argv.slice(2)))
}
