/**
 * Hold `wiki/llms-full.txt` to the pages it inlines.
 *
 * The bundle is generated by `wiki/.vitepress/gen-llms-full.mjs`, which reads
 * every published page and writes its body into a `<doc path="…">` section.
 * `wiki/AGENTS.md` makes regenerating it after a content change a hard rule —
 * "✅ Always: … regenerate `llms-full.txt` after content changes" — and until
 * this file nothing in the repository held that rule. A page edited without the
 * regeneration ships, and the readers who consume `llms-full.txt` are served
 * the old text while the site serves the new.
 *
 * ## Why the two guards that already read the bundle do not close this
 *
 * Both read it as a *witness* for a rule of their own, and neither compares a
 * section with its page:
 *
 * - `check-wiki-io-claim.ts` scans it for the retired I/O wording and takes its
 *   `<doc path="…">` list as proof the page scan reached the published wiki.
 * - `check-wiki-source-anchors.ts` resolves every citation in it, attributing
 *   each to the page whose section holds it.
 *
 * Each catches a stale bundle only when the staleness happens to show as a
 * finding. Measured on `3af8ec1` and reproduced on `cfcaf0b`: repoint one
 * anchor on `getting-started/policy-authoring.md` from `lib.rs#L57-L152` to
 * `lib.rs#L57-L151` — both valid, both opening on the same line — leave the
 * bundle alone, and `bun scripts/check-wiki-source-anchors.ts` exits 0 with
 * "1098 citation(s) resolve". Each copy resolves on its own terms. "The
 * generated bundle is current" is a different invariant from "every citation
 * resolves": a different failure mode, and a single-command remedy rather than
 * a rewrite. That is why it lives in its own script rather than as a third rule
 * inside a module whose doc comment describes a different contract, which is
 * also the shape of every other `scripts/check-*.ts` here — one invariant each.
 *
 * ## How it decides
 *
 * It calls {@link renderBundle} — the generator's own function, exported for
 * this — and compares its bytes against the committed file. The alternative
 * considered was to rebuild each section here from
 * `stripFrontmatter(readFileSync(page)).trimEnd()`, the way the generator does.
 * That re-implements the generator's contract in a second place, where it can
 * drift from the generator exactly the way the bundle drifts from the pages —
 * the same defect one level up, and a checker that is wrong in the direction of
 * passing. Calling the generator cannot drift, because it *is* the generator.
 *
 * The verdict is whole-file byte equality and nothing else: {@link
 * compareBundle} returns no problems if and only if the two strings are equal.
 * Everything below that is a *message*. A difference is attributed to the page
 * whose `<doc>` section holds it, because "you edited `quick-start.md` and did
 * not regenerate" is the sentence a contributor can act on, and a difference
 * that falls outside every section — the header, the spacing between two of
 * them, anything after the last one — is reported as that. The attribution
 * reuses {@link bundleSections}, the index `check-wiki-source-anchors.ts`
 * already builds over this format, rather than adding a second parser for it.
 * If that attribution is ever wrong — a page whose own prose holds a line
 * starting `<doc ` or `</doc>` at column 1 would confuse it — the finding moves
 * but the verdict does not, and the remedy printed is the same either way.
 *
 * ## What it does not cover, so it is not read as more than it is
 *
 * **It judges the copy, not the original.** That every section matches its page
 * says nothing about whether the page is right: a citation that resolves to the
 * wrong lines, a claim no source supports, the retired I/O wording — all of
 * those are faithfully copied into a bundle this calls current. Those are the
 * two sibling guards' and review's, and this one is what stops a *third* copy
 * of the question from appearing, by making the bundle a byte-exact function of
 * the pages rather than a second place a sentence can be wrong on its own.
 *
 * **It does not ask whether the generator bundles the right pages.** The page
 * list lives in `gen-llms-full.mjs` and is compared only against itself, so a
 * page added to the wiki and not added to that list is absent from the bundle
 * and current by this rule. `index.md` is deliberately absent for that reason,
 * which is why the gap cannot be closed by globbing here; #270 owns it.
 *
 * It is enforced by its own test rather than by a `ci.yml` step, the way both
 * sibling guards are: it reads the working tree and needs no build, so `bun
 * test` in the `js` job already runs it, and a contributor running the suite
 * locally gets the answer CI will.
 *
 * Usage:
 *   bun scripts/check-wiki-bundle-current.ts
 */

import { readFileSync } from 'node:fs'
import process from 'node:process'
import { BUNDLE_PATH, PAGE_COUNT, renderBundle } from '../wiki/.vitepress/gen-llms-full.mjs'
import { bundleSections } from './check-wiki-source-anchors'

/** The generated bundle, repo-relative, as findings label it. */
const LLMS_FULL = 'wiki/llms-full.txt'

/** The generator, repo-relative — the `where` for a finding about the build. */
const GENERATOR = 'wiki/.vitepress/gen-llms-full.mjs'

/** The one remedy every finding here has. */
const REGENERATE = '`cd wiki && bun .vitepress/gen-llms-full.mjs`'

export interface Problem {
  where: string
  detail: string
}

/** One `<doc>…</doc>` span of a bundle, as the text it holds. */
interface Chunk {
  page: string
  text: string
}

/**
 * Split a bundle into its sections, each as the lines it spans.
 *
 * Diagnostic only — see the module doc. Applied to the generator's output and
 * to the committed file alike, so a format this cannot read misattributes both
 * sides symmetrically rather than inventing a difference between them.
 */
function chunks(source: string): Chunk[] {
  const lines = source.split('\n')
  return bundleSections(source).map(({ line, end, page }) => ({
    page,
    text: lines.slice(line - 1, end).join('\n'),
  }))
}

/** `a` and `b` as the same pages in the same order, counting repeats. */
function samePages(a: Chunk[], b: Chunk[]): boolean {
  return a.length === b.length && a.every((chunk, index) => chunk.page === b[index]!.page)
}

/**
 * Which pages one side names and the other does not, in the order they appear.
 *
 * Reported by name rather than by count: a bundle that lost a page and a bundle
 * that gained one are different edits with the same arithmetic.
 */
function missingFrom(these: Chunk[], those: Chunk[]): string[] {
  const named = new Set(those.map(({ page }) => page))
  return [...new Set(these.map(({ page }) => page))].filter(page => !named.has(page))
}

/**
 * Every way the committed bundle differs from what the generator would write.
 *
 * Empty **if and only if** `actual === expected`. The localization below can
 * only decide *which* finding to report, never whether there is one: the
 * equality above is the whole verdict, and the fallback at the end is what
 * keeps a difference the attribution cannot place from reading as a pass.
 */
export function compareBundle(expected: string, actual: string): Problem[] {
  if (actual === expected) {
    return []
  }

  const want = chunks(expected)
  const have = chunks(actual)

  if (!samePages(want, have)) {
    const dropped = missingFrom(want, have)
    const extra = missingFrom(have, want)
    const detail = dropped.length === 0 && extra.length === 0
      ? `inlines the same pages in a different order from the one ${GENERATOR} writes them in`
      : [
          dropped.length > 0 ? `does not inline ${dropped.map(page => `\`${page}\``).join(', ')}` : '',
          extra.length > 0 ? `inlines ${extra.map(page => `\`${page}\``).join(', ')}, which the generator does not` : '',
        ].filter(Boolean).join('; ')
    return [{
      where: LLMS_FULL,
      detail: `${detail} — regenerate it: ${REGENERATE}`,
    }]
  }

  const stale = want
    .filter(({ text }, index) => text !== have[index]!.text)
    .map(({ page }): Problem => ({
      where: LLMS_FULL,
      detail: `its \`${page}\` section is not that page's current content — the page was edited `
        + 'without regenerating the bundle, so an LLM reader consuming this file is served the '
        + `old text while the site serves the new. Regenerate it: ${REGENERATE}`,
    }))
  if (stale.length > 0) {
    return stale
  }

  return [{
    where: LLMS_FULL,
    detail: `differs from what ${GENERATOR} writes, outside every \`<doc>\` section — its header, `
      + `the spacing between two sections, or something after the last one. Regenerate it: ${REGENERATE}`,
  }]
}

/**
 * The committed bundle, or the finding that it could not be read.
 *
 * Read from {@link BUNDLE_PATH}, the path the generator writes to, rather than
 * from a second spelling of it here — so the file this compares is the file
 * `bun .vitepress/gen-llms-full.mjs` would overwrite, and a future move of the
 * bundle cannot leave the check reading the old location and passing.
 */
function committed(): { text: string } | { problem: Problem } {
  try {
    return { text: readFileSync(BUNDLE_PATH, 'utf8') }
  }
  catch (error) {
    return {
      problem: {
        where: LLMS_FULL,
        detail: `could not be read (${(error as Error).message}) — write it with ${REGENERATE}`,
      },
    }
  }
}

export function checkRepository(): Problem[] {
  let expected: string
  try {
    expected = renderBundle()
  }
  catch (error) {
    // The generator reads each page it lists, so a page renamed or deleted
    // without updating the list lands here. Reported rather than thrown: a
    // stack trace out of a guard reads as the guard being broken, and the
    // repository state it describes is a real finding about the wiki.
    return [{
      where: GENERATOR,
      detail: `could not build the bundle to compare against (${(error as Error).message}) — a `
        + 'page it lists was renamed or deleted, so fix its page list first',
    }]
  }

  const file = committed()
  return 'problem' in file ? [file.problem] : compareBundle(expected, file.text)
}

export function main(): number {
  const problems = checkRepository()

  if (problems.length > 0) {
    for (const { where, detail } of problems) {
      console.error(`${where}: ${detail}`)
    }
    console.error(
      `\nwiki bundle: ${problems.length} problem(s). \`wiki/llms-full.txt\` is generated from the `
      + 'pages it inlines and committed alongside them, so every content change owes it a '
      + `regeneration — ${REGENERATE} — which \`wiki/AGENTS.md\` requires and this is what holds.`,
    )
    return 1
  }

  console.log(
    `wiki bundle: llms-full.txt is byte-identical to the ${PAGE_COUNT} pages it inlines`,
  )
  return 0
}

if (import.meta.main) {
  process.exit(main())
}
